### ISSUE TITLE
How to analyze a simple .o file?

### ISSUE THREAD

**Issue by BBge** [GrammaTech/ddisasm#37]
Hi, I want to use ddisasm to analyze one simple .o file, but it shows that the file could not be disassembled.
I am wondering how to solve this issue?
Thanks!
![image](https://user-images.githubusercontent.com/18453645/137802461-52e7d410-115f-4b7e-afda-d6fb1390b0a3.png)

**Comment by aeflores** [comment]
Hi @BBge, currently Ddisasm cannot disassemble .o object files correctly. This is due to a few differences between executables and object files, the main reason being that sections in object files are not allocated to specific virtual addresses.

However, this is a capability that we are working on, I will let you know once object files are supported.

**Comment by aeflores** [comment]
Hi @BBge , Ddisasm can now disassemble object files.
