### ISSUE TITLE
GTIRB IR file generated GTIRB IR file can't be printed in gtirb-pprint

### ISSUE THREAD

**Issue by StarGazerM** [GrammaTech/ddisasm#49]
Hi :
   I am trying to print the  gtirb file generated by ddisasm to asm file, it used to work well but now always printed as blank after I both upgrade ddisasm and pprinter. I also tried `--asm` flag, asm file is printed normally 
   my ddisasm version is  1.5.3 (UNKNOWN 2022-04-28) 
   my gtirb-pprinter version is 1.8.3 (UNKNOWN 2022-04-27)
  
  the  generated gtirb file is here
   https://drive.google.com/file/d/1TVv0X-LGag1nIrpozvk81f8h8jNy10FV/view?usp=sharing

**Comment by adamjseitz** [comment]
We've seen this internally as well where ddisasm and gtirb-pprinter versions were out of sync due to a recent breaking change. It looks like your builds are from the end of April, so they aren't the absolute latest.

Are you building from source? If so, can you try rebuilding/reinstalling both ddisasm (from main branch) and gtirb-pprinter (from master branch)? If not from source, how did you install ddisasm?

**Comment by aeflores** [comment]
Closing this for now, please reopen if this becomes an issue again.
